repos:
    - repo: local
      hooks:
          - id: pre-commit-script
            name: pre-commit-sh
            entry: scripts/pre-commit.sh
            language: script
            pass_filenames: false
            verbose: true
            # args: ['-v']
